### ISSUE TITLE
Update this repository to the currently available version on modrinth

### ISSUE THREAD

**Issue by stedwesd** [RooXChicken/toggleable-piechart#1]
I was looking towards modifying the mod to save my pie-chart configuration across multiple minecraft sessions, only to realize that the version here is heavily outdated compared to the one that I downloaded from modrinth.

It would be highly appreciated if you would update the source code of the mod in this repository (or that you make the piechart position, size, etc be saved across multiple sessions :D), or link me somewhere where I could find the updated source code.

Thanks in advance!

**Comment by RooXChicken** [comment]
Sorry about that. The git is now updated with the latest changes. 1.20.4 is on the `main` branch and 1.20.1 is on the `1.20.1` branch. If what you mean by `cross-session saving` as saving the settings to a file, I'm not sure why I haven't done that yet as I have a framework for this, and will actually start work on that now. If it's something else, I would love to see how you implement your idea. Let me know if you have any questions about the code. Thank you!

**Comment by stedwesd** [comment]
Oh yeah, that's what I meant with `cross-session saving`😅. Thanks for updating the repository!
